name: Reusable Workflow

on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
      input2:
        required: true
        type: string


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Echo input1    
      run: echo "${{ inputs.input1 }}"
    - name: Clear npm cache
      run: npm cache clean --force
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test